# _______________________________________________________Files in Python______________________________________________
# f=open("FirstFile.txt","r")   
# f=open("FirstFile.txt","rb")  
# f=open("FirstFile.txt","rt")  
# content=f.read()
# content=f.read(8)
# print(content)
# print(f.readline())
# print(f.read())
# print(f.readlines())
# for line in f:
#     print(line,end="")
# f=open("FirstFile.txt","a")
# f.write("\nI am from Madhepura, bihar")   
# a=f.write("\nHello Vivek") 
# print(a)  .
# f=open("FirstFile.txt","w")
# f.write("My name is Vivek Kumar")
# print(f.read())
# f=open("FirstFile.txt","r")
# print(f.read())
# f.write("Thank You\n")
# f.write("\nWait for next Assignment..")
# print(f.read())
# f.close()